---
title: "data-cleaning"
author: "Thien An Tran, Tejasree Kandibanda, Matthew Huang, Chloe Anbarcioglu"
format: 
  html:
    embed-resources: true
    code-tools: true
    toc: true
editor: source
execute: 
  error: true
  echo: true
  message: false
  warning: false
---

## Setup

```{r setup}
library("tidyverse")
murder <- read_csv("data/murder_total_deaths.csv")
happiness <- read_csv("data/hapiscore_whr.csv")
population <- read_csv("data/pop.csv")
```

## Data Cleaning

```{r}
convert_value <- function(val) {
  val <- as.character(val)
  
  multiplier <- case_when(
    str_detect(val, "k") ~ 1e3,
    str_detect(val, "M") ~ 1e6,
    str_detect(val, "B") ~ 1e9,
    TRUE ~ 1
  )
  
  numeric_value <- as.numeric(str_remove_all(val, "[kMB]"))
  
  return(numeric_value * multiplier)
}
```

### Converting Murder Counts to Numeric

```{r}
murder_clean <- murder |>
  select(country, `2005`:`2019`) |> 
  pivot_longer(cols = `2005`:`2019`,
               names_to = "year",
               values_to = "murder_count") |> 
  mutate(across(murder_count, ~convert_value(.)))

murder_clean
```

### Converting Population to Numeric

```{r}
population_clean <- population |>
  select(country, `2005`:`2019`) |>
  pivot_longer(cols = `2005`:`2019`,
               names_to = "year",
               values_to = "population") |>
  mutate(across(population, ~convert_value(.)))

population_clean
```

### Getting the Murder Rate for each Country and Year

```{r}
murder_pop_merged <- murder_clean |>
  inner_join(population_clean, by = c("country", "year"))

murder_rate_clean <- murder_pop_merged |>
  mutate(murder_rate_per_100k = (murder_count / population) * 100000)

murder_rate_clean
```

### Joining Datasets
