---
title: "STAT331 Final Project - Linear Regression"
author: "Thien An Tran, Tejasree Kandibanda, Matthew Huang, Chloe Anbarcioglu"
format: 
  html:
    embed-resources: true
    code-tools: true
    toc: true
editor: source
execute: 
  error: true
  echo: true
  message: false
  warning: false
code-fold: true
---

## Setup

```{r}
library(tidyverse)
library(here)

happiness_merged <- read_csv(here::here("data", "murder_happiness.csv"))
```

## Data Visualizations

### Plot 1:

```{r}
average_data <- happiness_merged |>
  group_by(year) |>
  summarise(avg_murder_rate = mean(murder_rate_per_100k),
            avg_happiness_score = mean(happiness_score))

ggplot(average_data, 
       aes(x = year, 
           y = avg_murder_rate)
       ) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, linetype = "dashed", color = "black") +
  labs(title = "Relationship Between Murder Rate and Happiness Score",
       x = "Average Murder Rate (per 100k)", y = "Average Happiness Score") +
  theme_minimal()
```

```{r}
ggplot(average_data, 
       aes(x = year, 
           y = avg_happiness_score)
       ) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, linetype = "dashed", color = "black") +
  labs(title = "Relationship Between Murder Rate and Happiness Score",
       x = "Average Murder Rate (per 100k)", y = "Average Happiness Score") +
  scale_x_log10() +
  theme_minimal()
```

### Plot 2:

```{r}
ggplot(average_data, aes(x = avg_murder_rate, y = avg_happiness_score)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE, linetype = "dashed", color = "black") +
  labs(title = "Relationship Between Murder Rate and Happiness Score",
       x = "Average Murder Rate (per 100k)", y = "Average Happiness Score") +
  theme_minimal()


```

